default:
  golem_name: experiencesdashboard
  golem_version: 0.4.2
  app_prod: no
  open: yes
production:
  app_prod: yes
dev:
  golem_wd: !expr here::here()
open:
  trust_name: demo_trust
  comment_1: Comments
trust_a:
  trust_name: trust_a
  comment_1: What could be improved?
  comment_2: What did we do well?
  question_1: fft
  location_1: Division
  location_2: Directorate
  location_3: Team
  gender: TRUE
  age: TRUE
  ethnicity: TRUE
trust_b:
  trust_name: trust_b
  comment_1: Comments
  question_1: fft
  location_1: Location 1
  location_2: Location 2
  location_3: Location 3
trust_c:
  trust_name: trust_c
  comment_1: Why did you answer this way?
  comment_2: Please tell us anything we could have done better
  question_1: fft
  location_1: Location 1
  location_2: Location 2
  location_3: Location 3
  gender: TRUE
  age: TRUE
  ethnicity: TRUE
trust_d:
  trust_name: trust_d
  comment_1: Comment 1
  question_1: fft
  location_1: Location 1
  location_2: Location 2
  location_3: Location 3
trust_e:
  trust_name: trust_e
  comment_1: What was good about your visit?
  comment_2: What would have made your visit better?
  question_1: fft
  location_1: Location 1
  location_2: Location 2
  location_3: Location 3
  gender: TRUE
  age: TRUE
  ethnicity: TRUE
care_opinion:
  trust_name: care_opinion
  comment_1: Story
  location_1: Service code
nhs_uk:
  trust_name: nhs_uk
  comment_1: Story

